version: 2

project_name: helm-oci-proxy

builds:
  - main: ./cmd/main.go
    binary: helm-oci-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - "ghcr.io/tuananh/{{ .ProjectName }}:nightly-amd64"
    dockerfile: Dockerfile
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - pkg/
      
  - image_templates:
      - "ghcr.io/tuananh/{{ .ProjectName }}:nightly-arm64"
    dockerfile: Dockerfile
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - pkg/

docker_manifests:
  - name_template: ghcr.io/tuananh/{{ .ProjectName }}:nightly
    image_templates:
      - ghcr.io/tuananh/{{ .ProjectName }}:nightly-amd64
      - ghcr.io/tuananh/{{ .ProjectName }}:nightly-arm64

# This ensures GoReleaser doesn't require a git tag for releases
release:
  disable: true 