name: Nightly Build

on:
  schedule:
    # Run at 1 AM GMT+7 (18:00 UTC previous day)
    - cron: '0 18 * * *'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create 0.0.0-nightly tag
        run: |
          if git rev-parse --verify 0.0.0-nightly >/dev/null 2>&1; then
            git tag -d 0.0.0-nightly
            git push origin :refs/tags/0.0.0-nightly
          fi
          git tag 0.0.0-nightly
          git push origin 0.0.0-nightly

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
